//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmacia
    {
        public int idfarmacia { get; set; }
        public string nombre_farmacia { get; set; }
        public string atencion_al_cliente { get; set; }
        public string pagina_web { get; set; }
    }
}
