//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmacia
    {
        public int ID_FARMACIA { get; set; }
        public string NOMBRE_FARMACIA { get; set; }
        public string ATENCION_AL_CLIENTE { get; set; }
        public string PAGINA_WEB { get; set; }
    }
}
