//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.sucursal_producto = new HashSet<sucursal_producto>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public int ID_PRESENTACION { get; set; }
        public int ID_CATEGORIA { get; set; }
        public int ID_LABORATORIO { get; set; }
        public string PRODUCTO1 { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] IMAGEN_PRODUCTO { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual laboratorio laboratorio { get; set; }
        public virtual presentacion presentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursal_producto> sucursal_producto { get; set; }
    }
}
