//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal_producto
    {
        public int id_sucursal_producto { get; set; }
        public int id_sucursal { get; set; }
        public int id_producto { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public int existencia { get; set; }
        public decimal precio { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
