//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal_producto
    {
        public int ID_SUCURSAL_PRODUCTO { get; set; }
        public int ID_SUCURSAL { get; set; }
        public int ID_PRODUCTO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public int EXISTENCIA { get; set; }
        public decimal PRECIO { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
